# AJUSTES DE PLANTILLAS DE EMAIL
mail.sender.user=your.email@gmail.com
mail.sender.user-alias=Money Fy
mail.sender.pwd=your_email_password
mail.support.money.fy=support.email@gmail.com

mail.subject.auth-code=Código de confirmación
mail.template.auth-code=emails/auth-code-email

mail.subject.user-account-activated=Cuenta de usuario activada
mail.template.user-account-activated=emails/user-account-activated

mail.subject.user-account-disabled=Cuenta de usuario desactivada
mail.template.user-account-disabled=emails/user-account-disabled

mail.subject.nova-user-referred=Nuevo usuario referido
mail.template.nova-user-referred=emails/nova-user-referred

mail.subject.quoter-details-purchaser=Nueva cotización en proceso - N°
mail.template.quoter-details-purchaser=emails/quoter-details-purchaser

mail.subject.vehicle-details-user=Nueva cotización vinculada a tu cuenta - N°
mail.template.vehicle-details-user=emails/vehicle-details-user

mail.subject.notify-account-not-found=Cuenta de comisiones indefinida
mail.template.notify-account-not-found=emails/notify-account-not-found

mail.subject.notify-conflictive-payment=Inconveniente con tu pago de comisiones
mail.template.notify-conflictive-payment=emails/conflictive-payment

# MoneyFy Data
# El secreto JWT ahora se gestiona exclusivamente mediante la variable de entorno del S.O. - Variable de entorno esperada: MONEYFY_JWT_SECRET
moneyfy.seeders.auto-enabled=false
moneyfy.commissions.level1=${COMMISSION_LEVEL1:35000}
moneyfy.commissions.level2=${COMMISSION_LEVEL2:10000}
moneyfy.commissions.level3=${COMMISSION_LEVEL3:5000}

# UF API
uf.base-url=https://api.cmfchile.cl/api-sbifv3/recursos_api/uf
uf.api-key=YOUR_UF_API_KEY

# BCI API
bci.qa.old.tarifacion.api-key=YOUR_BCI_OLD_API_KEY
bci.qa.old.tarifacion.url=https://apitarificacion.qa.bciseguros.cl/api/Tarificacion
bci.qa.base-url=https://apigw.qa.bciseguros.cl/ApiCotizadores
bci.qa.user=YOUR_BCI_USER
bci.qa.password=YOUR_BCI_PASSWORD

# FDI API
fdi.qa.base-url=https://api-qa.fidseguros.com
fdi.qa.version=1.0
fdi.qa.api-key=YOUR_FDI_API_KEY
fdi.qa.broker-id=YOUR_FDI_BROKER_ID
fdi.qa.update-endpoint.contractor-email=YOUR_FDI_CONTRACTOR_EMAIL
fdi.qa.update-endpoint.payer-email=YOUR_FDI_PAYER_EMAIL

# Administrador Root
moneyfy.admin.email=root.moneyfy@gmail.com
moneyfy.admin.password=Testing_123
moneyfy.admin.name=Root
moneyfy.admin.surname=MoneyFy
