# AJUSTES DE PLANTILLAS DE EMAIL
mail.sender.user=moneyfyapp@gmail.com
mail.sender.user-alias=Money Fy
mail.sender.pwd=udtx dnrt mpaf bieb
mail.support.money.fy=moneyfyapp@gmail.com

mail.subject.auth-code=Código de confirmación
mail.template.auth-code=emails/auth-code-email

mail.subject.user-account-activated=Cuenta de usuario activada
mail.template.user-account-activated=emails/user-account-activated

mail.subject.user-account-disabled=Cuenta de usuario desactivada
mail.template.user-account-disabled=emails/user-account-disabled

mail.subject.nova-user-referred=Nuevo usuario referido
mail.template.nova-user-referred=emails/nova-user-referred

mail.subject.quoter-details-purchaser=Nueva cotización en proceso - N°
mail.template.quoter-details-purchaser=emails/quoter-details-purchaser

mail.subject.vehicle-details-user=Nueva cotización vinculada a tu cuenta - N°
mail.template.vehicle-details-user=emails/vehicle-details-user

mail.subject.notify-account-not-found=Cuenta de comisiones indefinida
mail.template.notify-account-not-found=emails/notify-account-not-found

# DATA PARA CONSTRUIR REPORTE DE COMISIONES
report.commission.cutoff-date=5
report.commission.payment-date=10

# MoneyFy Data
moneyfy.api-key=C1LB4PKD3RY0WL4R3N3G

# UF API
uf.base-url=https://api.cmfchile.cl/api-sbifv3/recursos_api/uf
uf.api-key=19f3f6dee45cb9f6ae124fe0c12742ebebcfdaba

# BCI API
bci.tarifacion.api-key=95OkbvNW.SA0J861eME6xRqqKyYJz4iW90zpFcHv0gmdjR4OEUxM=
bci.tarifacion.url=https://apitarificacion.qa.bciseguros.cl/api/Tarificacion

# FDI API
fdi.qa.base-url=https://api-qa.fidseguros.com
fdi.qa.version=1.0
fdi.qa.api-key=eyJvcmciOiI2NDVlNzM4NWJhMjA3MDAwMDFmYmU0MDgiLCJpZCI6IjI2MzcxZjllZTM2YTQzMzQ4NjkyYjYyNjg4YjQ3ZjU4IiwiaCI6Im11cm11cjEyOCJ9
fdi.qa.broker-id=11.111.111-1
fdi.qa.update-endpoint.contractor-email=nuser.random@gmail.com
fdi.qa.update-endpoint.payer-email=nuser.random01@gmail.com
